version: '3.9'

services:
  prisma-postgres-dev:
    container_name: integration-dev-prisma
    image: postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: dev
    volumes:
      - ./postgres-data:/var/lib/postgresql/data